language: php
php:
  - "5.4"
  - "5.3"
before_install:
  - php /home/travis/.phpenv/versions/5.3/bin/composer self-update
  - php /home/travis/.phpenv/versions/5.4/bin/composer self-update
before_script:
  - composer install
  - composer selfupdate
script: phpunit --configuration phpunit.xml --coverage-text