language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - php /home/travis/.phpenv/versions/5.3.26/bin/composer.phar self-update